
Problema 1
```{r}
#1.1 Se crean los vectores para los 5 estudiantes
E_1 <- c(50.4,62.3,92.1,77.6,TRUE)
E_2 <- c(41.7,87.9,75.3,72.4,FALSE)
E_3 <- c(30.3,67.8,69.3,71.2,FALSE)
E_4 <- c(65.4,85.1,92.3,96.8,TRUE)
E_5 <- c(70.4,88.2,95.2,90.7,TRUE)


#1.2 Se crea un vector de los 5 estudiantes
students_vector <- c(E_1,E_2,E_3,E_4,E_5)

#1.3 Construya una matriz
students_matrix <- matrix(students_vector,ncol=5,byrow = TRUE)
students_matrix

```
Problema 2
```{r}
#2.1 Cree vectores para los nombres
name_students <- c("Lili Brown","Davis Moore","Susan Taylor", "Mike Jones","Tom Hill")
name_courses_legal_age <- c("TIC","Accounting","Psychology","Ethics","Legal_age")
#2.2 Nombre filas y columnas de matriz
colnames(students_matrix) <- name_courses_legal_age
rownames(students_matrix) <- name_students
students_matrix

```
Problema 3

```{r}
#3.1 Se crea el vector para el total por estudiante

total_grade_student <- rowSums(students_matrix[,c(1:4)])
total_grade_student

#3.2 Unir el total a la matriz
result_students <- cbind(students_matrix,total_grade_student)
result_students
```
Problema 4
```{r}
#4.1 Seleccione elementos e imprima el resultado
select_elements = result_students[c(1,3,5),c(2:4)]
select_elements
```
Problema 5
```{r}
#5.1 Construir un dataframe a partir de matriz
TIC = result_students[,1]
Accounting = result_students[,2]
Phychology = result_students[,3]
Ethics = result_students[,4]
Legal_age = result_students[,5]
total_grade_student = result_students[,6]
students_grade_df = data.frame(TIC,Accounting,Phychology,Ethics,Legal_age,total_grade_student)
students_grade_df

```
```{r}

#5.2 Filtrar con subset
result_students[,5]
condicion_1 <- (Accounting>80)
condicion_2 <- (result_students[,5]>0)
criterio <- condicion_1 & condicion_2
subset(students_grade_df,subset=criterio)
```

Problema 6

```{r}
students_projection <- function(matriz){
  for (i in 1:nrow(matriz)){
    for(j in 1:(ncol(matriz)-2)){
      if (matriz[i,j]<=45){    
        print("Student at risk")}
        else if( matriz[i,j]>45 & matriz[i,j]<61){
          print("Student may be approved")
        }
        else{print("Student approved")}
    }
  }
}

students_projection(result_students)
```

Problema 7 
```{r}
#7.1 Crear una funcion
index_education <- function(grade){
  (1+(grade/100))/2
}
#7.2 Seleccionar datos
all_students_grade = students_grade_df[,c(1:4)]
students_grade
```
```{r}
#Aplicar lappy
lapply(students_grade,index_education)


```

Problema 8

```{r}
#Obtener promedio por asignatura
score_mean=apply(result_students[,c(1:4)],2,mean)
score_mean

```

